%CREATEFIGURE(EPS1,YMATRIX1)
%  EPS1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 23-May-2010 21:41:06

% Create figure
figure1 = figure('PaperSize',[20.98 29.68]);

% Create axes
axes('Parent',figure1,'XTick',[0.01 0.05 0.09 0.13 0.17 0.21 0.25],...
     'Position',[0.05273 0.051 0.919 0.874]);
% axes1 = axes('Parent',figure1,...
%     'YTickLabel',{'0','5000','10000','15000','20000'},...
%     'YTick',[0 5000 1e+004 1.5e+004 2e+004],...
%     'XTick',[0.01 0.05 0.09 0.13 0.17 0.21 0.25],...
%     'Position',[0.08475 0.051 0.887 0.874]);
% Uncomment the following line to preserve the X-limits of the axes
xlim([0.01 0.25]);
grid('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(eps, min(transBound(1, :),1),'LineWidth',2);
plot2 = plot(eps, min(transBound(2, :),1), 'LineWidth', 2);
% plot1 = plot(eps, vapnikBound,'LineWidth',2);
% plot2 = plot(eps, vapnikStratBound, 'LineWidth', 2);
% plot3 = plot(eps, uniformBonferonniBound, 'LineWidth', 2);
set(plot1,'Color', 'r');
set(plot2,'Color', 'g');
%set(plot3,'Color', 'm');

% Create xlabel


